
export const COURSE_SAVE_START = 'COURSE_SAVE_START';
export const COURSE_SAVE_SUCCESS = 'COURSE_SAVE_SUCCESS';
export const COURSE_SAVE_FAILURE = 'COURSE_SAVE_FAILURE';

export const COURSE_FETCH_START = 'COURSE_FETCH_START';
export const COURSE_FETCH_SUCCESS = 'COURSE_FETCH_SUCCESS';
export const COURSE_FETCH_FAILURE = 'COURSE_FETCH_FAILURE';

export const STUDENT_SAVE_START = 'STUDENT_SAVE_START';
export const STUDENT_SAVE_SUCCESS = 'STUDENT_SAVE_SUCCESS';
export const STUDENT_SAVE_FAILURE = 'STUDENT_SAVE_FAILURE';

export const STUDENT_FETCH_START = 'STUDENT_FETCH_START';
export const STUDENT_FETCH_SUCCESS = 'STUDENT_FETCH_SUCCESS';
export const STUDENT_FETCH_FAILURE = 'STUDENT_FETCH_FAILURE';

export const AUTH_SAVE_START = 'AUTH_SAVE_START';
export const AUTH_SAVE_SUCCESS = 'AUTH_SAVE_SUCCESS';
export const AUTH_SAVE_FAILURE = 'AUTH_SAVE_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
